const data = [
    // ---------------- MEDICAMENTOS  -------------
    { id: 1, nombre: "Paracetamol 500mg - Blíster 10 un.", precio: 2.50, categoria: "medicamentos", imagen: "Paracetamol.png" },
    { id: 2, nombre: "Ibuprofeno 400mg - Blíster 10 un.", precio: 10.00, categoria: "medicamentos", imagen: "Ibuprofeno.webp" },
    { id: 3, nombre: "Amoxicilina 500mg - Caja x 100", precio: 35.00, categoria: "medicamentos", imagen: "Amoxicilina.jpg" },
    { id: 4, nombre: "Omeprazol 20mg - Blíster 10 un.", precio: 12.20, categoria: "medicamentos", imagen: "Omeprazol.webp" },
    { id: 5, nombre: "Loratadina 10mg - Blíster 10 un.", precio: 5.20, categoria: "medicamentos", imagen: "Loratadina.webp" },
    { id: 6, nombre: "Diclofenaco 50mg - Blíster 10 un.", precio: 9.20, categoria: "medicamentos", imagen: "Diclofenaco.jpg" },
    { id: 7, nombre: "Aspirina 100mg Bayer - Caja x 28", precio: 16.80, categoria: "medicamentos", imagen: "Aspirina.jpg" },
    { id: 8, nombre: "Losartán 50mg - Blíster 10 un.", precio: 8.90, categoria: "medicamentos", imagen: "Losartan.webp" },
    { id: 9, nombre: "Metformina 850mg - Blíster 10 un.", precio: 8.60, categoria: "medicamentos", imagen: "Metformina.webp" },
    { id: 10, nombre: "Azitromicina 500mg - Caja x 3 un.", precio: 35.60, categoria: "medicamentos", imagen: "Azitromicina.webp" },
    { id: 11, nombre: "Naproxeno 550mg - Blíster 10 un.", precio: 14.50, categoria: "medicamentos", imagen: "Naproxeno.webp" },
    { id: 12, nombre: "Cetirizina 10mg - Blíster 10 un.", precio: 4.80, categoria: "medicamentos", imagen: "cetirizina.jpg" },
    { id: 13, nombre: "Ciprofloxacino 500mg - Blíster 10 un.", precio: 18.90, categoria: "medicamentos", imagen: "Ciprofloxacino.jpg" },
    { id: 14, nombre: "Dexametasona 4mg - Ampolla", precio: 6.50, categoria: "medicamentos", imagen: "Dexametasona.jpg" },
    { id: 15, nombre: "Salbutamol Inhalador 100mcg", precio: 22.50, categoria: "medicamentos", imagen: "Salbutamol.png" },
    { id: 16, nombre: "Atorvastatina 20mg - Blíster 10 un.", precio: 28.00, categoria: "medicamentos", imagen: "Atorvastatina.jpg" },
    { id: 17, nombre: "Enalapril 20mg - Blíster 10 un.", precio: 7.30, categoria: "medicamentos", imagen: "Enalapril.webp" },
    { id: 18, nombre: "Fluconazol 150mg - Cápsula", precio: 15.00, categoria: "medicamentos", imagen: "Fluconazol.jpg" },
    { id: 19, nombre: "Tramadol 50mg - Blíster 10 un.", precio: 21.40, categoria: "medicamentos", imagen: "Tramadol.webp" },
    { id: 20, nombre: "Clotrimazol Crema Tópica 1% 20g", precio: 11.20, categoria: "medicamentos", imagen: "Clotrimazol.jpg" },

    // -------------- CUIDADO PERSONAL  -------------
    { id: 21, nombre: "Shampoo Anticaspa LIFE 600ml FOR-MEN", precio: 15.00, categoria: "cuidado", imagen: "ShampoLife.jpg" },
    { id: 22, nombre: "Jabón Líquido Antibacterial 360ml-Manzana", precio: 17.80, categoria: "cuidado", imagen: "JabonLiquido.webp" },
    { id: 23, nombre: "Crema Hidratante POND'S 50gr", precio: 31.00, categoria: "cuidado", imagen: "Ponds.jpg" },
    { id: 24, nombre: "Desodorante Spray NIVEA 150ml-Pearl Beauty", precio: 12.00, categoria: "cuidado", imagen: "Desodorante.webp" },
    { id: 25, nombre: "Pasta Dental Oral-B 75ml", precio: 17.50, categoria: "cuidado", imagen: "Oral-B.webp" },
    { id: 26, nombre: "Enjuague Bucal Colgate PLAX Soft Mint 500ml", precio: 14.50, categoria: "cuidado", imagen: "Colgate.webp" },
    { id: 27, nombre: "Crema de Afeitar Gillette Foamy Sensitive 179ml", precio: 40.50, categoria: "cuidado", imagen: "Crema-Afeitar.webp" },
    { id: 28, nombre: "Loción Humectante Nivea Body Corporal 500ml", precio: 45.00, categoria: "cuidado", imagen: "Locion-Nivea.avif" },
    { id: 29, nombre: "Gel Fijador Xtreme Hold Ultra-Suave 320gr", precio: 19.00, categoria: "cuidado", imagen: "Gel-Fijador.webp" },
    { id: 30, nombre: "Protector Solar Bahía DRY-TOUCH 150ml SPF 50+", precio: 47.00, categoria: "cuidado", imagen: "Bloqueador-Solar.jpeg" },
    { id: 31, nombre: "Acondicionador Pantene Restauración 400ml", precio: 18.50, categoria: "cuidado", imagen: "Pantene.webp" },
    { id: 32, nombre: "Jabón Aval Antibacterial Pack x 3", precio: 10.20, categoria: "cuidado", imagen: "AVAL3.webp" },
    { id: 33, nombre: "Hilo Dental Reach Menta con Cera 50m", precio: 9.50, categoria: "cuidado", imagen: "Hilo-Dental.webp" },
    { id: 34, nombre: "Toallas Higiénicas Nosotras Buenas Noches x 10", precio: 8.50, categoria: "cuidado", imagen: "Nosotras.webp" },
    { id: 35, nombre: "Crema Corporal Palmer's Manteca de Cacao Post-Parto 250ml", precio: 35.00, categoria: "cuidado", imagen: "Aceite-Palma.webp" },
    { id: 36, nombre: "Desodorante Rexona Clinical Classic Roll-on 50ml", precio: 22.00, categoria: "cuidado", imagen: "Rexona.webp" },
    { id: 37, nombre: "Máquina de Afeitar Desechable Gillette Prestobarba3 Sport 2un", precio: 14.00, categoria: "cuidado", imagen: "Prestobarba.webp" },
    { id: 38, nombre: "Hisopos Johnson's Flexibles x 100", precio: 6.50, categoria: "cuidado", imagen: "Hisopos.webp" },
    { id: 39, nombre: "Talco para Pies REXONA Efficient Original Frasco 200g", precio: 16.80, categoria: "cuidado", imagen: "Talco.webp" },
    { id: 40, nombre: "Gel Limpiador Facial Neutrogena Purified Skin 150g", precio: 38.90, categoria: "cuidado", imagen: "Neutrogena.webp" },

    // ---------------- CUIDADO BEBÉ  ----------------
    { id: 41, nombre: "Pañales Huggies Active Sec Xtra Flex Talla G", precio: 42.00, categoria: "bebe", imagen: "Huggies.webp" },
    { id: 42, nombre: "Toallitas Húmedas Tuinies Paquete x 25", precio: 4.00, categoria: "bebe", imagen: "ToallitasKuromi.webp" },
    { id: 43, nombre: "Ungüento Derma bebé Aloe Vera y Manzanilla", precio: 18.50, categoria: "bebe", imagen: "UnguentoDerma.webp" },
    { id: 44, nombre: "Philips Biberón Avent Natural 3.0 Vidrio 120ml", precio: 85.00, categoria: "bebe", imagen: "Biberon.webp" },
    { id: 45, nombre: "Fórmula NAN 1 Infantil 1.1kg", precio: 120.50, categoria: "bebe", imagen: "NAN.webp" },
    { id: 46, nombre: "Chupón Ortodóntico Nuby Azul", precio: 12.00, categoria: "bebe", imagen: "Chupon.webp" },
    { id: 47, nombre: "ATTITUDE, Baby Leaves™, Shampoo & Body 473 ml", precio: 30.00, categoria: "bebe", imagen: "Champu-Baby.avif" },
    { id: 48, nombre: "Aceite JOHNSON'S BABY Original 300ml", precio: 12.50, categoria: "bebe", imagen: "Aceite.webp" },
    { id: 49, nombre: "Aspirador Nasal RHINOPHAR", precio: 37.00, categoria: "bebe", imagen: "Aspirador.webp" },
    { id: 50, nombre: "Termómetro para Baño Birdies Beige Suavinex", precio: 48.00, categoria: "bebe", imagen: "Termometro.webp" },
    { id: 51, nombre: "Colonia Baby Magic Mennen 200ml", precio: 54.70, categoria: "bebe", imagen: "MENNEN.webp" },
    { id: 52, nombre: "Crema Cero para Rozaduras 110g", precio: 82.00, categoria: "bebe", imagen: "Crema-cero.webp" },
    { id: 53, nombre: "Fórmula Enfamil Premium 1 (0-6) meses 800g", precio: 135.00, categoria: "bebe", imagen: "Enfamil.webp" },
    { id: 54, nombre: "Mordedor Enfriable Estrella Refrigerante Pigeon", precio: 25.00, categoria: "bebe", imagen: "Mordedor.webp" },
    { id: 55, nombre: "Baberos Desechables x 20 unidades", precio: 22.90, categoria: "bebe", imagen: "Baberos.webp" },
    { id: 56, nombre: "Esponja de Baño Natural para Bebé", precio: 35.50, categoria: "bebe", imagen: "Esponja.webp" },
    { id: 57, nombre: "Hisopos de Seguridad de Algodón Q-Soft x 30", precio: 12.20, categoria: "bebe", imagen: "HisoposBaby.webp" },
    { id: 58, nombre: "Pañales Pampers Premium Care Talla M x 60", precio: 72.00, categoria: "bebe", imagen: "Pampers.webp" },
    { id: 59, nombre: "Esterilizador de Biberones para Microondas AVENT", precio: 285.00, categoria: "bebe", imagen: "Estirilizador.webp" },
    { id: 60, nombre: "Loción Hidratante Mustela 300ml", precio: 59.00, categoria: "bebe", imagen: "MustelaLocion.avif" },

    // ---------------- VITAMINAS Y SUPLEMENTOS ----------------
    { id: 61, nombre: "Vitamina C 1000mg x 100 Tabletas", precio: 62.50, categoria: "vitaminas", imagen: "VitaminaC.avif" },
    { id: 62, nombre: "Zinc Quelado CENTURY 21ST 50mg x 60 Cápsulas", precio: 22.00, categoria: "vitaminas", imagen: "Zinc.avif" },
    { id: 63, nombre: "Citrato de Magnesio SMART BLENDS 400gr", precio: 85.00, categoria: "vitaminas", imagen: "Magnesio.webp" },
    { id: 64, nombre: "Complejo B x 30 Cápsulas", precio: 28.50, categoria: "vitaminas", imagen: "ComplejoB.avif" },
    { id: 65, nombre: "Omega 3 Fish Oil Mason Natural 1000 mg Envase 60 Und", precio: 32.00, categoria: "vitaminas", imagen: "FishOil.webp"},
    { id: 66, nombre: "Nutricost Calcio con Vitamina C x 60 Tablet", precio: 32.00, categoria: "vitaminas", imagen: "VitaminaD.avif" },
    { id: 67, nombre: "Colágeno Hidrolizado en Polvo 300gr", precio: 67.00, categoria: "vitaminas", imagen: "Colageno.webp" },
    { id: 68, nombre: "Multivitamínico Centrum x 30 Tabletas", precio: 58.00, categoria: "vitaminas", imagen: "Centrum.webp" },
    { id: 69, nombre: "Hierro en Gomitas Sabor Uva x 60", precio: 32.00, categoria: "vitaminas", imagen: "Hierro-Gomitas.avif" },
    { id: 70, nombre: "Vitamina k 1,100 x180 capsulas BRONSON", precio: 158.00, categoria: "vitaminas", imagen: "VitaminaK.webp" },
    { id: 71, nombre: "Vitamina D3 2000 UI x 90 Cápsulas", precio: 85.00, categoria: "vitaminas", imagen: "VitaminaD3.avif" },
    { id: 72, nombre: "Magnesol Efervescente Naranja x 33", precio: 35.50, categoria: "vitaminas", imagen: "Magnesol.webp" },
    { id: 73, nombre: "Gomitas de Melatonina 5mg para dormir Sabor Mnazana x 60", precio: 62.00, categoria: "vitaminas", imagen: "Melatonina.webp" },
    { id: 74, nombre: "Biotina Natures's Bounty 10,000 mcg para Cabello y Uñas", precio: 155.00, categoria: "vitaminas", imagen: "Biotina.webp" },
    { id: 75, nombre: "Ensure Advance Polvo Vainilla 850g", precio: 115.00, categoria: "vitaminas", imagen: "Ensure.jpg" },
    { id: 76, nombre: "Glucosamina + Condroitina x 60", precio: 88.00, categoria: "vitaminas", imagen: "Glucosamina.avif" },
    { id: 77, nombre: "Supradyn Efervescente x 10", precio: 22.00, categoria: "vitaminas", imagen: "Supradyn.jpg" },
    { id: 78, nombre: "Vitamina E 400 UI x 100 Cápsulas Blanda", precio: 49.00, categoria: "vitaminas", imagen: "VitaminaE.jpg" },
    { id: 79, nombre: "Probióticos Probullín 10 Billones CFU x 30", precio: 75.00, categoria: "vitaminas", imagen: "Probioticos.avif" },
    { id: 80, nombre: "Ácido Fólico 800 mcg x 100 Tabletas", precio: 28.00, categoria: "vitaminas", imagen: "Acido-Folico.png" },

    // ---------------- EQUIPOS MÉDICOS  --------------
    { id: 81, nombre: "Termómetro Digital de contacto Microlife MT3001", precio: 22.00, categoria: "equipos", imagen: "TermDigital.webp" },
    { id: 82, nombre: "Tensiómetro Aneroide RIESTER 1350", precio: 450.00, categoria: "equipos", imagen: "Tensiometro.webp" },
    { id: 83, nombre: "Oxímetro de Pulso Digital ChoiceMMed", precio: 126.00, categoria: "equipos", imagen: "Oximetro.webp" },
    { id: 84, nombre: "Nebulizador a Pistón LUDGA LDG 8614", precio: 179.00, categoria: "equipos", imagen: "Nebulizador.webp" },
    { id: 85, nombre: "Glucómetro Accu-Chek Instant Kit", precio: 140.00, categoria: "equipos", imagen: "Glucometro.webp" },
    { id: 86, nombre: "Tiras Reactivas Accu-Chek Guide x 50", precio: 109.00, categoria: "equipos", imagen: "Tiras-Reactivas.png" },
    { id: 87, nombre: "Lancetas para Glucosa Labmedical x 100", precio: 30.00, categoria: "equipos", imagen: "Lancetas.jpg" },
    { id: 88, nombre: "Muletas de Aluminio Care Par Talla M", precio: 120.00, categoria: "equipos", imagen: "Muletas.webp" },
    { id: 89, nombre: "Faja Sacro Lumbar Ortopédica Talla L", precio: 84.00, categoria: "equipos", imagen: "Faja-Dorso.webp" },
    { id: 90, nombre: "Cabestrillo de Doble Sujeción Talla XL", precio: 45.00, categoria: "equipos", imagen: "Cabestrillo.webp" },
    { id: 91, nombre: "Tensiómetro Digital Omron de Brazo", precio: 180.00, categoria: "equipos", imagen: "Tensiometro-Brazo.jpg" },
    { id: 92, nombre: "Termómetro Infrarrojo Digital a Distancia", precio: 105.00, categoria: "equipos", imagen: "Infrarrojo.webp" },
    { id: 93, nombre: "Silla de Ruedas Estándar de Acero", precio: 550.00, categoria: "equipos", imagen: "SillaRuedas.webp" },
    { id: 94, nombre: "Andador de Aluminio Plegable Adulto", precio: 270.00, categoria: "equipos", imagen: "Andador.jpg" },
    { id: 95, nombre: "Bastón Ortopédico Ajustable", precio: 79.00, categoria: "equipos", imagen: "Baston.webp" },
    { id: 96, nombre: "Collarín Cervical Blando Ortopédico", precio: 48.00, categoria: "equipos", imagen: "Collarin.webp" },
    { id: 97, nombre: "Medias de Compresión Antivarices", precio: 65.00, categoria: "equipos", imagen: "Medias.jpg" },
    { id: 98, nombre: "Estetoscopio Littmann Classic III", precio: 780.00, categoria: "equipos", imagen: "Estetoscopio.webp" },
    { id: 99, nombre: "Balanza Digital de Baño de Vidrio Max.180kg", precio: 59.00, categoria: "equipos", imagen: "Balanza-Vidrio.webp" },
    { id: 100, nombre: "Almohadilla Térmica Menstrual Portátil con Calor Ajustable y Batería Recargable TASHINE", precio: 95.00, categoria: "equipos", imagen: "Almohadilla-Termica.webp" },

    // ---------------- HIGIENE Y PROTECCIÓN  ----------------
    { id: 101, nombre: "Mascarilla KN95 Certificada x 10 un.", precio: 12.50, categoria: "proteccion", imagen: "KN95.webp" },
    { id: 102, nombre: "Caja para Instrumental Quirúrgico", precio: 28.00, categoria: "proteccion", imagen: "Caja-Instrumental.webp" },
    { id: 103, nombre: "Alcohol en Gel Neutro Family Care 1L", precio: 23.00, categoria: "proteccion", imagen: "Alcohol-Neutro.webp" },
    { id: 104, nombre: "Alcohol Líquido 70° EBRIEL 1L", precio: 14.00, categoria: "proteccion", imagen: "Alcohol-Ebriel.webp" },
    { id: 105, nombre: "Guantes de Látex Alkhofar Talla S x 100", precio: 23.00, categoria: "proteccion", imagen: "Guantes.webp" },
    { id: 106, nombre: "Careta Facial Protectora con Rachet", precio: 29.00, categoria: "proteccion", imagen: "Careta.webp" },
    { id: 107, nombre: "Mascarilla Quirúrgica 3 Pliegues x 50", precio: 15.00, categoria: "proteccion", imagen: "3Pliegues.jpg" },
    { id: 108, nombre: "Toallitas Desinfectantes Clorox x 15", precio: 7.00, categoria: "proteccion", imagen: "Toallitas-Clorox.webp" },
    { id: 109, nombre: "Traje Bioseguridad Nivel Aislamiento", precio: 25.00, categoria: "proteccion", imagen: "Trajes-Desechables.png" },
    { id: 110, nombre: "Cubrezapatos Descartables x 100", precio: 19.00, categoria: "proteccion", imagen: "Cubrezapatos.webp" },
    { id: 111, nombre: "Gorros Descartables tipo Enfermera x 100", precio: 11.00, categoria: "proteccion", imagen: "Gorro-Descartable.jpg" },
    { id: 112, nombre: "Jabón Antibacterial Protex Herbal 120g", precio: 4.50, categoria: "proteccion", imagen: "Protex-Herbal.webp" },
    { id: 113, nombre: "Guantes de Nitrilo Talla M x 100 un.", precio: 17.00, categoria: "proteccion", imagen: "Guantes-Nitrilo.jpg" },
    { id: 114, nombre: "Dispensador de Alcohol Automático 500ml", precio: 65.00, categoria: "proteccion", imagen: "Dispensador.webp" },
    { id: 115, nombre: "Lentes de Bioseguridad Anti-empañantes", precio: 48.00, categoria: "proteccion", imagen: "Gafas-Seguridad.jpg" },
    { id: 116, nombre: "Desinfectante Amonio Cuaternario Daryza Concentrado Litro Galón 5 Litro", precio: 65.00, categoria: "proteccion", imagen: "Desinfectante-Amonio.webp" },
    { id: 117, nombre: "Pediluvio Bandeja Desinfectante de Calzado", precio: 30.00, categoria: "proteccion", imagen: "Pediluvio.webp" },
    { id: 118, nombre: "Mandilón Descartable Celulósico x 10", precio: 40.00, categoria: "proteccion", imagen: "Mandilon.webp" },
    { id: 119, nombre: "Lejía Clorox Tradicional Botella 1 Kg", precio: 5.50, categoria: "proteccion", imagen: "Lejia-Clorox.webp" },
    { id: 120, nombre: "Papel Toalla Elite Doble Hoja PLUS x 2oo Mt", precio: 26.50, categoria: "proteccion", imagen: "Elite.webp" }
];

   